# Deploy notes
# library(rsconnect)
# connectCloudUser()
# rsconnect::deployApp()

name: Deploy surveydown app to Posit Connect

on:
  schedule:
    # Every hour, at the start of the hour (UTC)
    - cron: "0 * * * *"

  # Allow manual deployments
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Posit Connect
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: rocker/r-ver:4.6.1

    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Install Linux system dependencies
        run: |
          apt-get update
          apt-get install libcurl4-openssl-dev

      - name: Install renv and restore from renv.lock
        run: |
          Rscript --vanilla -e \
            'install.packages("renv", repos = "https://cran.rstudio.com"); renv::restore(lockfile = "sota2026/renv.lock", prompt = FALSE); surveydown::sd_version()'
            